[package]
name = "common-device"
version = "0.1.0"
edition = "2021"

[lib]
name = "ares_device_lib"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
home = "0.5.4"
log = "0.4.17"
pathdiff = "0.2.1"

[features]
picker = []