[workspace]
members = ["common", "ares-package", "ares-install", "ares-push"]

[patch.crates-io]
libssh-rs = { git = "https://github.com/wez/libssh-rs.git", rev = "74d845c1696b710b8b8388e193b3882c15edf2c1" }
libssh-rs-sys = { git = "https://github.com/wez/libssh-rs.git", rev = "74d845c1696b710b8b8388e193b3882c15edf2c1" }