[workspace]
members = [
    "common/device",
    "common/connection",
    "ares-package",
    "ares-install",
    "ares-push",
    "ares-launch",
    "ares-device",
]

[patch.crates-io]
libssh-rs = { git = "https://github.com/mariotaku/libssh-rs.git", branch = "feature/more-auth-options" }
libssh-rs-sys = { git = "https://github.com/mariotaku/libssh-rs.git", branch = "feature/more-auth-options" }
