[workspace]
resolver = "2"
members = [
    "common/device",
    "common/connection",
    "ares-package",
    "ares-install",
    "ares-push",
    "ares-launch",
    "ares-device",
]

[workspace.dependencies]
clap = "4.2.4"
serde = "1.0.160"
serde_json = "1.0.96"
libssh-rs = "0.2.0"
sha256 = "1.1.3"
regex = "1.8.1"
indicatif = "0.17.7"

[patch.crates-io]
libssh-rs = { git = "https://github.com/mariotaku/libssh-rs.git", branch = "feature/more-auth-options" }
libssh-rs-sys = { git = "https://github.com/mariotaku/libssh-rs.git", branch = "feature/more-auth-options" }
