[package]
name = "ares-device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
clap = { version = "4.2.4", features = ["derive", "env"] }

[build-dependencies]
embed-manifest = "1.3.1"