[package]
name = "ares-package"
version = "0.1.2"
edition = "2021"
authors = ["Mariotaku Lee <mariotaku.lee@gmail.com>"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.4", features = ["derive", "env"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
ar = "0.9.0"
tar = "0.4.38"
flate2 = "1.0"
path-slash = "0.2.1"
elf = "0.7.2"
regex = "1.8.1"
walkdir = "2.3.3"

[package.metadata.deb]
section = "devel"