name: Build Test

on:
  push:
    # Don't run for tags
    tags-ignore:
      - 'v*.*.*'
    branches:
      - '**'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Build Dependencies
        run: sudo apt install -yq libgtk-3-dev

      - name: Use Rust Stable
        run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build Packages
        run: |
          for f in ares-*; do
            cargo deb -p "$f" || exit 1
          done